### ISSUE TITLE
Add more filters for what is allowed not allowed

### ISSUE THREAD

**Issue by peternied** [peternied/discerning-merger#1]
Often blanket "this file is OK to edit" isn't granular enough, especially when those files can control broad behavior such as `build.gradle` where completely different behavior could be allowed by allowed authors.

It would be much better if changes could be authorized based on 'how much different' the line is, such as the following.

There are serveral kinds of calcuations that could be done, such as lines changed, which is easily available from git diff, or hamming distance and for the following to lines the answer is 1, indicating not very different where the 13 became 14.

```
  opensearch_version = System.getProperty("opensearch.version", "1.3.13-SNAPSHOT")
```

```
  opensearch_version = System.getProperty("opensearch.version", "1.3.14-SNAPSHOT")
```

See also [1] _How to get an edit-distance between two commits?_ as another way to indicate

- [1] https://stackoverflow.com/questions/23974443/how-to-get-an-edit-distance-between-two-commits

Possible update could look include settings like the following:
```
inputs:
  ...
  max-files-changed:
    description: "The max number of files that are allowed to be modified"
    default: -1
    required: false
  max-files-lines-changed:
    description: "The max number of lines that are allowed to be modified"
    default: -1
    required: false
  max-difference-total:
    description: "Hamming distance is calculated on every changed line, the max number of character changes in this PR that is allowed"
    default: -1
    required: false
  max-difference-file:
    description: "Hamming distance is calculated on every changed line, the max number of character changes in a single file"
    default: -1
    required: false
  max-difference-line:
    description: "Hamming distance is calculated on every changed line, the max number of character changes in every line"
    default: -1
    required: false
```
